// stratum/cmd/icons regenerates static/icons.svg AND the inline
// sprite block in design-system/index.html from the manifest at
// static/icons.txt. One run rewrites both — they're guaranteed to
// stay in sync.
//
// Why two outputs:
//   - static/icons.svg is the production sprite consumers reference
//     via <use href="/static/icons.svg#NAME"/>.
//   - design-system/index.html opens via file:// when run via
//     `make design-system`; <use href="../static/icons.svg#…"> is
//     unreliable in Chromium under file://. The inline copy lives
//     between <!-- inline-sprite:begin --> / :end markers and is
//     rewritten by this tool, not by hand.
//
// Manifest line forms:
//   <name>            — fetched from Lucide via unpkg.
//   <name> | <url>    — fetched from any URL (used for brand icons
//                        Lucide doesn't ship, e.g. github).
//
// Each source SVG is parsed: viewBox is preserved, and the styling
// (outline-stroke vs filled) is auto-detected from the presence of
// `stroke=` on the root element. Lucide icons all have stroke attrs
// so they render as outlines; Simple Icons brand SVGs have neither
// stroke nor fill at the root and render as solid currentColor.
//
// Run via `make icons-sync`. Re-runnable safely.

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

const (
	manifestPath     = "static/icons.txt"
	spritePath       = "static/icons.svg"
	designSystemPath = "design-system/index.html"
	lucideBase       = "https://unpkg.com/lucide-static/icons/"

	inlineBeginMarker = "<!-- inline-sprite:begin -->"
	inlineEndMarker   = "<!-- inline-sprite:end -->"
)

type spec struct {
	name string
	url  string
}

func main() {
	specs, err := readManifest(manifestPath)
	if err != nil {
		fail("read manifest: %v", err)
	}
	if len(specs) == 0 {
		fail("manifest %s is empty", manifestPath)
	}

	symbols := make([]string, 0, len(specs))
	for _, s := range specs {
		body, err := fetch(s.url)
		if err != nil {
			fail("fetch %s (%s): %v", s.name, s.url, err)
		}
		sym, err := buildSymbol(s.name, body)
		if err != nil {
			fail("build %s: %v", s.name, err)
		}
		symbols = append(symbols, sym)
	}

	if err := writeExternalSprite(symbols); err != nil {
		fail("write external sprite: %v", err)
	}
	fmt.Printf("wrote %s — %d icons\n", spritePath, len(symbols))

	if err := writeInlineSprite(symbols); err != nil {
		fail("write inline sprite: %v", err)
	}
	fmt.Printf("wrote inline block in %s\n", designSystemPath)
}

func writeExternalSprite(symbols []string) error {
	var sprite strings.Builder
	sprite.WriteString(`<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by stratum/cmd/icons. DO NOT EDIT BY HAND.
  Add a name to icons.txt and run `)
	sprite.WriteString("`make icons-sync`")
	sprite.WriteString(` to regenerate.

  Outline icons from Lucide (https://lucide.dev) — ISC, with the
  Feather subset under MIT. Full text in icons.LICENSE.txt.
  Brand icons from Simple Icons (https://simpleicons.org) — CC0.

  Reference from any HTML with:
    <svg class="icon"><use href="/static/icons.svg#NAME"/></svg>
  Stroke / fill bind to currentColor, so the icon picks up the
  colour of its containing element via CSS.
-->
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
`)
	for _, sym := range symbols {
		sprite.WriteString(sym)
	}
	sprite.WriteString("</svg>\n")
	return os.WriteFile(spritePath, []byte(sprite.String()), 0o644)
}

// writeInlineSprite finds the marker pair in design-system/index.html
// and rewrites everything between (exclusive) with a fresh
// <svg style="display:none"> block carrying every symbol. The
// markers stay put so the next run can find them again.
func writeInlineSprite(symbols []string) error {
	src, err := os.ReadFile(designSystemPath)
	if err != nil {
		return err
	}
	begin := bytes.Index(src, []byte(inlineBeginMarker))
	end := bytes.Index(src, []byte(inlineEndMarker))
	if begin < 0 || end < 0 || end < begin {
		return fmt.Errorf("markers not found in %s — paste %q and %q around the inline-sprite block once",
			designSystemPath, inlineBeginMarker, inlineEndMarker)
	}

	var inline strings.Builder
	inline.WriteString(inlineBeginMarker)
	inline.WriteString("\n<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display:none\">\n")
	for _, sym := range symbols {
		inline.WriteString(sym)
	}
	inline.WriteString("</svg>\n")

	out := make([]byte, 0, len(src))
	out = append(out, src[:begin]...)
	out = append(out, []byte(inline.String())...)
	out = append(out, src[end:]...)
	return os.WriteFile(designSystemPath, out, 0o644)
}

func readManifest(path string) ([]spec, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var out []spec
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, parseLine(line))
	}
	return out, scanner.Err()
}

func parseLine(line string) spec {
	parts := strings.SplitN(line, "|", 2)
	name := strings.TrimSpace(parts[0])
	if len(parts) == 1 {
		return spec{name: name, url: lucideBase + name + ".svg"}
	}
	return spec{name: name, url: strings.TrimSpace(parts[1])}
}

func fetch(url string) (string, error) {
	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	return string(body), nil
}

var (
	rootSVGRe   = regexp.MustCompile(`(?s)<svg([^>]*)>(.*)</svg>`)
	viewBoxRe   = regexp.MustCompile(`viewBox="([^"]+)"`)
	strokeAttRe = regexp.MustCompile(`\bstroke=`)
	whitespace  = regexp.MustCompile(`\s+`)
	titleTagRe  = regexp.MustCompile(`(?s)<title>.*?</title>`)
)

const (
	outlineAttrs = `fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"`
	filledAttrs  = `fill="currentColor"`
)

// buildSymbol turns a fetched SVG into a single <symbol> line.
// Preserves the source viewBox; picks outline-stroke or filled
// styling based on whether the source SVG has a stroke attribute
// on its root element.
func buildSymbol(name, body string) (string, error) {
	m := rootSVGRe.FindStringSubmatch(body)
	if m == nil {
		return "", fmt.Errorf("no <svg>...</svg>")
	}
	rootAttrs := m[1]
	inner := m[2]

	vb := viewBoxRe.FindStringSubmatch(rootAttrs)
	if vb == nil {
		return "", fmt.Errorf("no viewBox")
	}
	viewBox := vb[1]

	style := filledAttrs
	if strokeAttRe.MatchString(rootAttrs) {
		style = outlineAttrs
	}

	// Strip <title> — accessible name comes from aria-label on the
	// host <svg> element, not from the symbol.
	inner = titleTagRe.ReplaceAllString(inner, "")
	inner = whitespace.ReplaceAllString(strings.TrimSpace(inner), " ")

	return fmt.Sprintf("  <symbol id=%q viewBox=%q %s>%s</symbol>\n", name, viewBox, style, inner), nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
